source "https://rubygems.org"

gem 'sinatra'

group :test, :development do
  gem "rspec"
  gem 'rack-test'
  gem 'cucumber'
  gem 'capybara', '>= 2.17.0'
  gem 'selenium-webdriver'
  gem 'webrat'
  gem 'simplecov', require: false
  gem 'rake'
end
