source "https://rubygems.org"

gem 'sinatra'

group :test, :development do
  gem "rspec"
  gem 'rack-test'
  gem 'cucumber'
  gem 'capybara'
  gem 'selenium-webdriver', '>= 3.11.0'
  gem 'webrat'
  gem 'simplecov', require: false
  gem 'rake'
end
