source "https://rubygems.org"

gem 'sinatra', '>= 2.0.1'

group :test, :development do
  gem "rspec"
  gem 'rack-test', '>= 1.0.0'
  gem 'cucumber'
  gem 'capybara', '>= 2.17.0'
  gem 'selenium-webdriver'
  gem 'webrat', '>= 0.7.3'
  gem 'simplecov', require: false
  gem 'rake'
end
